language: go
script:
        - go test -v
        - go test -v github.com/vosst/csi/machine
        - go test -v github.com/vosst/csi/crash -httptest.serve=127.0.0.1:9090  
        - go test -v github.com/vosst/csi/cmd
notifications:
email: false
